name: Update Notebooks
on:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  update-notebooks:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:

    - name: See event name
      run: |
        echo "title ${title}"
        echo "actor ${actor}"
        echo "event_name ${event_name}"
      env:
        title: ${{ github.event.issue.title }}
        actor: ${{ github.actor }}
        event_name: ${{ github.event_name }}

    - name: Copy Repository Contents
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.7'

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: |
        sudo apt-get update -y
        pip3 install pandas numpy ipykernel jupyter altair altair_saver eland
        python3 -m ipykernel install --user --name python3
        npm install
        sudo chmod -R 777 .

    - name: crawl obituaries
      id: update_nb_crawl
      run: |
        npm run crawl

    - name: parse obituaries
      id: update_nb_parse
      run: |
        npm run parse

    - name: update notebooks
      id: update_nb
      run: |
        npm run notebook-weekly
        npm run notebook-monthly
        npm run notebook-boxplot

    - name: save notebooks & images
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add assets/vega_*.png
        git add data/tirol_obituaries_deduped.csv
        git add data/tirol_obituaries_deduped_weekly.csv
        git add data/tirol_obituaries_deduped_weekly_outlier_detection_features.csv
        git add docs/jupyter-notebook-weekly.html
        git add docs/data/metadata.json
        git add docs/data/vega_*.json
        git commit -m "[bot] refresh notebooks" || echo "No changes to commit"
        git push -f || echo "No changes to push"
